var AM_LIST = ['Katie Cartwright', 'Craig White', 'Paul Reeves', 'Suzanne Green', 'Thomas Henson'];

var STORES = [
  { id: 'albertstreet', name: 'Albert Street', am: 'Suzanne Green' },
  { id: 'alfreton', name: 'Alfreton', am: 'Craig White' },
  { id: 'allenton', name: 'Allenton', am: 'Paul Reeves' },
  { id: 'alvaston', name: 'Alvaston', am: 'Paul Reeves' },
  { id: 'ankirk', name: 'Anstey', am: 'Thomas Henson' },
  { id: 'arnold', name: 'Arnold', am: 'Craig White' },
  { id: 'ashbourne', name: 'Ashbourne', am: 'Suzanne Green' },
  { id: 'ashby', name: 'Ashby', am: 'Thomas Henson' },
  { id: 'bakeryshop', name: 'Bakery Shop', am: 'Suzanne Green' },
  { id: 'belper', name: 'Belper', am: 'Paul Reeves' },
  { id: 'beeston', name: 'Beeston', am: 'Craig White' },
  { id: 'bingham', name: 'Bingham', am: 'Katie Cartwright' },
  { id: 'borrowash', name: 'Borrowash', am: 'Suzanne Green' },
  { id: 'branston', name: 'Branston', am: 'Thomas Henson' },
  { id: 'bulwell', name: 'Bulwell', am: 'Katie Cartwright' },
  { id: 'burton', name: 'Burton', am: 'Thomas Henson' },
  { id: 'chaddesden', name: 'Chaddesden', am: 'Suzanne Green' },
  { id: 'chellaston', name: 'Chellaston', am: 'Suzanne Green' },
  { id: 'chilwell', name: 'Chilwell', am: 'Katie Cartwright' },
  { id: 'clifton', name: 'Clifton', am: 'Katie Cartwright' },
  { id: 'coalville', name: 'Coalville', am: 'Thomas Henson' },
  { id: 'derbioncrownwalk', name: 'Derbion Crown Walk', am: 'Suzanne Green' },
  { id: 'duffield', name: 'Duffield', am: 'Paul Reeves' },
  { id: 'eastleake', name: 'East Leake', am: 'Thomas Henson' },
  { id: 'eastwood', name: 'Eastwood', am: 'Paul Reeves' },
  { id: 'heanor', name: 'Heanor', am: 'Paul Reeves' },
  { id: 'hucknall', name: 'Hucknall', am: 'Paul Reeves' },
  { id: 'ilkeston', name: 'Ilkeston', am: 'Craig White' },
  { id: 'keyworth', name: 'Keyworth', am: 'Thomas Henson' },
  { id: 'lansdownedrive', name: 'Lansdowne Drive', am: 'Thomas Henson' },
  { id: 'lichfield', name: 'Lichfield', am: 'Thomas Henson' },
  { id: 'listergate', name: 'Lister Gate', am: 'Craig White' },
  { id: 'littleover', name: 'Littleover', am: 'Suzanne Green' },
  { id: 'longeaton', name: 'Long Eaton', am: 'Craig White' },
  { id: 'loughborough', name: 'Loughborough', am: 'Thomas Henson' },
  { id: 'mackworth', name: 'Mackworth', am: 'Paul Reeves' },
  { id: 'mansfield', name: 'Mansfield', am: 'Craig White' },
  { id: 'mapperley', name: 'Mapperley', am: 'Craig White' },
  { id: 'matlock', name: 'Matlock', am: 'Paul Reeves' },
  { id: 'melbourne', name: 'Melbourne', am: 'Suzanne Green' },
  { id: 'meltonroad', name: 'Melton Road', am: 'Katie Cartwright' },
  { id: 'mickleover', name: 'Mickleover', am: 'Suzanne Green' },
  { id: 'newark', name: 'Newark', am: 'Katie Cartwright' },
  { id: 'oakwood', name: 'Oakwood', am: 'Suzanne Green' },
  { id: 'parkfarm', name: 'Park Farm', am: 'Suzanne Green' },
  { id: 'radcliffe', name: 'Radcliffe', am: 'Katie Cartwright' },
  { id: 'ripley', name: 'Ripley', am: 'Paul Reeves' },
  { id: 'ruddington', name: 'Ruddington', am: 'Katie Cartwright' },
  { id: 'sinfin', name: 'Sinfin', am: 'Paul Reeves' },
  { id: 'southwell', name: 'Southwell', am: 'Katie Cartwright' },
  { id: 'spondon', name: 'Spondon', am: 'Paul Reeves' },
  { id: 'stretton', name: 'Stretton', am: 'Thomas Henson' },
  { id: 'sutton', name: 'Sutton', am: 'Katie Cartwright' },
  { id: 'suttonlakeside', name: 'Sutton Lakeside', am: 'Katie Cartwright' },
  { id: 'swadlincote', name: 'Swadlincote', am: 'Thomas Henson' },
  { id: 'tamworth', name: 'Tamworth', am: 'Thomas Henson' },
  { id: 'tealpark', name: 'Teal Park', am: 'Craig White' },
  { id: 'uttoxeter', name: 'Uttoxeter', am: 'Thomas Henson' },
  { id: 'victoriacentre', name: 'Victoria Centre', am: 'Katie Cartwright' },
  { id: 'westbridgford', name: 'West Bridgford', am: 'Craig White' },
  { id: 'wollaton', name: 'Wollaton', am: 'Craig White' }
];

function auditEmailForStore(name) {
  return name.replace(/\s+/g, '.') + '@birdsofderby.co.uk';
}
